baseURL = 'https://blog.yhy.gd.cn/'
languageCode = 'zh-cn'
title = '笨鸟先飞'
theme = "hugo-theme-monochrome"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
enableEmoji = true
enableGitInfo = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
pagerSize = 5

[frontmatter]
lastmod = ["lastmod", ":fileModTime"]

[services]
  [services.googleAnalytics]
    id = 'G-EZS77WS4T3'
