navbar_title = '笨鸟先飞'
footer = "Copyright © 2024 by yhy"
author = "yhy"
color_scheme = "dark"

enable_zooming_js = true
enable_header_anchor = true
enable_toc = true
enable_site_search="true"

# SEO
enable_open_graph = true
enable_twitter_cards = true

# Collapsible Menu
enable_collapsible_toc = false
enable_collapsible_changelogs = true

[list_layout]
enable_group_by_year = true
enable_show_date = true
enable_pagination = false

# syntax highlight settings
[syntax_highlight]
lib = "prism.js" # "builtin" | "prism.js"

    [syntax_highlight.builtin]
    enable_code_copy = true

    [syntax_highlight.prism]
    enable_code_copy = true
    enable_line_no = false

[page.comment]
enable = true
[page.comment.giscus]
enable = true
repo="1yhy/blog"
repoId = "R_kgDOM_m8YA"
category = "Announcements"
categoryId = "DIC_kwDOM_m8YM4CjUnL"
mapping = "pathname"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "1"
inputPosition = "bottom" # ["top", "bottom"]
lightTheme = "light"
darkTheme = "dark_tritanopia"
