[[navbar]]
  identifier = "posts"
  name = "文章"
  url = "/zh-cn/posts/"
  weight = 1

[[navbar]]
  identifier = "talks"
  name = "碎碎念"
  url = "/zh-cn/talks/"
  weight = 2

# [[navbar]]
#  identifier = "friends"
#  name = "友链"
#  url = "/zh-cn/friends/"
#  weight = 3

[[navbar]]
  identifier = "me"
  name = "关于"
  url = "/zh-cn/me/"
  weight = 4
