[[navbar]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 1

[[navbar]]
  identifier = "talks"
  name = "碎碎念"
  url = "/talks/"
  weight = 2

# [[navbar]]
#  identifier = "friends"
#  name = "友链"
#  url = "/friends/"
#  weight = 3

[[navbar]]
  identifier = "me"
  name = "关于"
  url = "/me/"
  weight = 4
