name: Auto publish to static website

on:
  push:
    branches:
      - master

jobs:
  hugo-publish:
    name: publish content to static website
    runs-on: ubuntu-latest
    steps:
      - name: checkout blog repo
        uses: actions/checkout@v2

      - name: setup hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: latest
          extended: true

      - name: build content to public site
        working-directory: ./
        run: hugo --minify --gc

      - name: install nodejs
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '20'

      - name: install tencent cloud cloudbase
        shell: bash
        run: npm i -g @cloudbase/cli

      - name: publish blog to tencent static site
        working-directory: ./public
        shell: bash
        run: |
          tcb login --apiKeyId ${{ secrets.QCLOUDAPIKEYID }} --apiKey ${{ secrets.QCLOUDAPIKEY }}
          tcb hosting deploy ./ -e ${{ secrets.QCLOUDENVID }}
